### ISSUE TITLE
What is the metric used in Table 3. Object Recognition Precision?

### ISSUE THREAD

**Issue by YuQiao0303** [ashawkey/dimr#6]
Hi author!
 Thank you for this amazing work!
I have a question about Table 3 in the paper namely Object Recognition Precision. I'm not sure what's the IoU used here. Is it the IoU between proposed instance points and GT instance points? Or the proposed bounding boxes and GT boxes?

Thank you !!

**Comment by ashawkey** [comment]
@YuQiao0303 Hi, it's between the bounding boxes.

**Comment by YuQiao0303** [comment]
> @YuQiao0303 Hi, it's between the bounding boxes.

I see. Thank you.
